name: React Filtering Movie Table Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      
      - name: Install dependencies
        working-directory: frontend
        run: |
            npm install
            npm install cross-env
      
      - name: Run tests
        run: npm test
